<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\common.props" />

  <PropertyGroup>
    <!-- Root Namespace -->
    <RootNamespace>PPWCode.Server.Core.NServiceBus</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <!-- PPWCode -->
    <PackageReference Include="PPWCode.Vernacular.NHibernate.III" />
    <PackageReference Include="PPWCode.Server.Core" />
    <PackageReference Include="PPWCode.API.Core" />

    <!-- NServiceBus -->
    <PackageReference Include="NServiceBus" />
  </ItemGroup>

</Project>
