<Project>

    <PropertyGroup>
        <!-- Enable central package management -->
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>

        <!-- Enforce versions also on transitive dependencies! -->
        <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>

        <!-- Enable floating versions -->
        <!-- This is not recommended but we do use package lock files -->
        <!-- So always review changes to package lock files to prevent pain -->
        <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>

        <!-- no overrides allowed, should only exceptionally be enabled -->
        <CentralPackageVersionOverrideEnabled>false</CentralPackageVersionOverrideEnabled>
    </PropertyGroup>

    <!-- package versions -->
    <ItemGroup>
        <!-- jetbrains -->
        <PackageVersion Include="JetBrains.Annotations" Version="2025.2.4" />

        <!-- ppwcode -->
        <PackageVersion Include="PPWCode.Vernacular.Contracts.I" Version="1.*" />
        <PackageVersion Include="PPWCode.Vernacular.Exceptions.IV" Version="2.*" />
        <PackageVersion Include="PPWCode.Vernacular.Semantics.IV" Version="2.*" />
        <PackageVersion Include="PPWCode.Vernacular.Persistence.IV" Version="2.*" />
        <PackageVersion Include="PPWCode.Vernacular.NHibernate.III" Version="5.*"/>
        <PackageVersion Include="PPWCode.API.Core" Version="3.*"/>
        <PackageVersion Include="PPWCode.Server.Core" Version="4.*" />

        <!-- newtonsoft -->
        <PackageVersion Include="Newtonsoft.Json" Version="13.*" />

        <!-- nhibernate -->
        <PackageVersion Include="NHibernate" Version="5.*" />
        <PackageVersion Include="NHibernateProfiler.Appender" Version="6.0.*"/>

        <!-- project specific -->
        <PackageVersion Include="NServiceBus" Version="7.*" />

        <!-- nunit -->
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.*" />
        <PackageVersion Include="NUnit" Version="4.*" />
        <PackageVersion Include="NUnit3TestAdapter" Version="6.*" />
        <PackageVersion Include="JunitXml.TestLogger" Version="8.*" />
        <PackageVersion Include="coverlet.collector" Version="10.*" />

        <!-- analyzers -->
        <PackageVersion Include="NUnit.Analyzers" Version="4.*" />
    </ItemGroup>

    <!-- microsoft: framework dependent -->
    <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
        <PackageVersion Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.*" />
        <PackageVersion Include="System.Configuration.ConfigurationManager" Version="8.*"/>
        <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="8.*" />
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
        <PackageVersion Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="9.*" />
        <PackageVersion Include="System.Configuration.ConfigurationManager" Version="9.*"/>
        <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="9.*" />
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
        <PackageVersion Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.*" />
        <PackageVersion Include="System.Configuration.ConfigurationManager" Version="10.*"/>
        <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.*" />
    </ItemGroup>

    <!-- global package references -->
    <ItemGroup>
        <!-- included in each project, using PrivateAssets="All" -->
        <GlobalPackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556" />
    </ItemGroup>

</Project>
